[package]
name = "raknet"
version = "0.1.0"
edition = "2021"

[dependencies]
binary = { path = "../binary" }
derive = { path = "../derive" }
bytes = "1.9.0"
tokio = { version = "1.41.1", features = ["full"] }
socket2 = "0.5.8"