use num_derive::{FromPrimitive, ToPrimitive};
use std::collections::HashMap;
use binary::{generate, Decode, Encode, Reader, v32, v64, w32, Writer};
use derive::{Decode, Encode};
use crate::nbt::{NetworkLittleEndian, NBT};
use crate::types::Vec3;
use crate::types::BlockPos;

generate!(EntityMetadata, <>, HashMap<u32, EntityDataEntry<'a>>, 'a);

impl<'a> Encode for EntityMetadata<'a> {
    fn encode(&self, w: &mut Writer) {
        w32::new(self.len() as u32).encode(w);

        let mut keys: Vec<&u32> = self.keys().collect();
        keys.sort();

        for key in keys.iter() {
            w32::new(**key).encode(w);
            self.val.get(key).unwrap().encode(w);
        }
    }
}

impl<'a> Decode<'a> for EntityMetadata<'a> {
    fn decode(r: &mut Reader<'a>) -> Option<Self> {
        let len = w32::decode(r)?.get() as usize;
        let data = (0..len).map(|_| {
            let key = w32::decode(r)?.get();
            let value = EntityDataEntry::decode(r)?;

            Some((key, value))
        }).collect::<Option<_>>()?;

        Some(Self::new(data))
    }
}

#[derive(Debug, Clone, Encode, Decode)]
pub struct EntityProperties {
    pub integer_properties: Vec<IntegerEntityProperty>,
    pub float_properties: Vec<FloatEntityProperty>,
}

#[derive(Debug, Clone, Encode, Decode)]
pub struct IntegerEntityProperty {
    pub index: w32,
    pub value: v32,
}

#[derive(Debug, Clone, Encode, Decode)]
pub struct FloatEntityProperty {
    pub index: w32,
    pub value: f32,
}

#[derive(Debug, Clone, PartialEq, Encode, Decode)]
#[encoding(type = w32)]
pub enum EntityDataEntry<'a> {
    U8(u8),
    I16(i16),
    I32(v32),
    F32(f32),
    String(String),
    NBT(NBT<'a, NetworkLittleEndian>),
    BlockPos(BlockPos),
    I64(v64),
    Vec3(Vec3),
}

#[derive(Debug, Copy, Clone, FromPrimitive, ToPrimitive)]
pub enum EntityDataKey {
    Flags,
    StructuralIntegrity,
    Variant,
    ColorIndex,
    Name,
    Owner,
    Target,
    AirSupply,
    EffectColor,
    EffectAmbience,
    JumpDuration,
    Hurt,
    HurtDirection,
    RowTimeLeft,
    RowTimeRight,
    Value,
    DisplayTileRuntimeID,
    DisplayOffset,
    CustomDisplay,
    Swell,
    OldSwell,
    SwellDirection,
    ChargeAmount,
    CarryBlockRuntimeID,
    ClientEvent,
    UsingItem,
    PlayerFlags,
    PlayerIndex,
    BedPosition,
    PowerX,
    PowerY,
    PowerZ,
    AuxPower,
    FishX,
    FishZ,
    FishAngle,
    AuxValueData,
    LeashHolder,
    Scale,
    HasNPC,
    NPCData,
    Actions,
    AirSupplyMax,
    MarkVariant,
    ContainerType,
    ContainerSize,
    ContainerStrengthModifier,
    BlockTarget,
    Inventory,
    TargetA,
    TargetB,
    TargetC,
    AerialAttack,
    Width,
    Height,
    FuseTime,
    SeatOffset,
    SeatLockPassengerRotation,
    SeatLockPassengerRotationDegrees,
    SeatRotationOffset,
    SeatRotationOffstDegrees,
    DataRadius,
    DataWaiting,
    DataParticle,
    PeekID,
    AttachFace,
    Attached,
    AttachedPosition,
    TradeTarget,
    Career,
    HasCommandBlock,
    CommandName,
    LastCommandOutput,
    TrackCommandOutput,
    ControllingSeatIndex,
    Strength,
    StrengthMax,
    DataSpellCastingColor,
    DataLifetimeTicks,
    PoseIndex,
    DataTickOffset,
    AlwaysShowNameTag,
    ColorTwoIndex,
    NameAuthor,
    Score,
    BalloonAnchor,
    PuffedState,
    BubbleTime,
    Agent,
    SittingAmount,
    SittingAmountPrevious,
    EatingCounter,
    FlagsTwo,
    LayingAmount,
    LayingAmountPrevious,
    DataDuration,
    DataSpawnTime,
    DataChangeRate,
    DataChangeOnPickup,
    DataPickupCount,
    InteractText,
    TradeTier,
    MaxTradeTier,
    TradeExperience,
    SkinID,
    SpawningFrames,
    CommandBlockTickDelay,
    CommandBlockExecuteOnFirstTick,
    AmbientSoundInterval,
    AmbientSoundIntervalRange,
    AmbientName,
    FallDamageMultiplier,
    NameRawText,
    CanRideTarget,
    LowTierCuredTradeDiscount,
    HighTierCuredTradeDiscount,
    NearbyCuredTradeDiscount,
    NearbyCuredDiscountTimeStamp,
    HitBox,
    IsBuoyant,
    FreezingEffectStrength,
    BuoyancyData,
    GoatHornCount,
    BaseRuntimeID,
    MovementSoundDistanceOffset,
    HeartbeatIntervalTicks,
    Heartbeat,
    PlayerLastDeathPosition,
    PlayerLastDeathDimension,
    PlayerHasDied,
    CollisionBox,
}

#[derive(Debug, Copy, Clone, FromPrimitive, ToPrimitive)]
pub enum EntityDataFlag {
    OnFire,
    Sneaking,
    Riding,
    Sprinting,
    UsingItem,
    Invisible,
    Tempted,
    InLove,
    Saddled,
    Powered,
    Ignited,
    Baby,
    Converting,
    Critical,
    ShowName,
    AlwaysShowName,
    NoAI,
    Silent,
    WallClimbing,
    Climb,
    Swim,
    Fly,
    Walk,
    Resting,
    Sitting,
    Angry,
    Interested,
    Charged,
    Tamed,
    Orphaned,
    Leashed,
    Sheared,
    Gliding,
    Elder,
    Moving,
    Breathing,
    Chested,
    Stackable,
    ShowBottom,
    Standing,
    Shaking,
    Idling,
    Casting,
    Charging,
    KeyboardControlled,
    PowerJump,
    Dash,
    Lingering,
    HasCollision,
    HasGravity,
    FireImmune,
    Dancing,
    Enchanted,
    ReturnTrident,
    ContainerPrivate,
    Transforming,
    DamageNearbyMobs,
    Swimming,
    Bribed,
    Pregnant,
    LayingEgg,
    PassengerCanPick,
    TransitionSitting,
    Eating,
    LayingDown,
    Sneezing,
    Trusting,
    Rolling,
    Scared,
    InScaffolding,
    OverScaffolding,
    DescendThroughBlock,
    Blocking,
    TransitionBlocking,
    BlockedUsingShield,
    BlockedUsingDamagedShield,
    Sleeping,
    WantsToWake,
    TradeInterest,
    DoorBreaker,
    BreakingObstruction,
    DoorOpener,
    Captain,
    Stunned,
    Roaring,
    DelayedAttack,
    AvoidingMobs,
    AvoidingBlock,
    FacingTargetToRangeAttack,
    HiddenWhenInvisible,
    InUI,
    Stalking,
    Emoting,
    Celebrating,
    Admiring,
    CelebratingSpecial,
    OutOfControl,
    RamAttack,
    PlayingDead,
    InAscendingBlock,
    OverDescendingBlock,
    Croaking,
    DigestMob,
    JumpGoal,
    Emerging,
    Sniffing,
    Digging,
    SonicBoom,
    HasDashTimeout,
    PushTowardsClosestSpace,
    Scenting,
    Rising,
    FeelingHappy,
    Searching,
    Crawling,
    TimerFlag1,
    TimerFlag2,
    TimerFlag3,
}
