[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
binary = { path = "../binary" }
derive = { path = "../derive" }
bytes = "1.8.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
